### ISSUE TITLE
cannot use the package because of deprecation

### ISSUE THREAD

**Issue by Yuanzhisheng** [jdoepfert/roipoly.py#23]
Now I am trying to install this package and run the basic_example, but when the picture shows, I when I click some point in the square, there is no response or red points to show the point.
It is said like that: 
zhangqianlindeMacBook-Pro:roipoly.py zhangqianlin$ python3 examples/basic_example.py
/Users/zhangqianlin/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2349: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(obj, collections.Iterator):
/Users/zhangqianlin/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2366: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return list(data) if isinstance(data, collections.MappingView) else data
Traceback (most recent call last):
  File "examples/basic_example.py", line 29, in <module>
    roi1.display_roi()
  File "/Users/zhangqianlin/anaconda3/lib/python3.7/site-packages/roipoly/roipoly.py", line 92, in display_roi
    line = plt.Line2D(self.x + [self.x[0]], self.y + [self.y[0]],
IndexError: list index out of range 

the version is python3.7 on the macOS.

LOOK FORWARD TO YOUR REPLY, THX!

**Comment by Yuanzhisheng** [comment]
hi, I am still very confused about how to run the examples. It presents a picture and then I try to click some points, but there is no response to that....may I ask the reason for that?

**Comment by jdoepfert** [comment]
Hi @Yuanzhisheng , the deprecation warning you see does not matter, it's rather the `IndexError: list index out of range`. Others have seen this error when starting python from an IDE, e.g. Spyder, rather than the terminal. I guess you are using the terminal though? 
I see you are using conda. Can you create a new conda environment, activate it and install the external libraries with `pip install -r requirements.txt`? And then try running the example again from the new environment and see if that works.

**Comment by jdoepfert** [comment]
@Yuanzhisheng any update on that issue?
